# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_id', models.CharField(max_length=100)),
                ('campus_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField()),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.IntegerField()),
                ('study_name', models.CharField(max_length=100)),
                ('study_campus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Campus')),
                ('study_school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.School')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('user_nickname', models.CharField(max_length=100)),
                ('user_lastName', models.CharField(max_length=100)),
                ('user_Password', models.CharField(max_length=100)),
                ('user_campus_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Campus')),
                ('user_school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.School')),
                ('user_study_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Study')),
            ],
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_school_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.School'),
        ),
    ]
