# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campuses'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'Studies'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_Password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_lastName',
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_info',
            field=models.CharField(default='no campus info', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='school_info',
            field=models.CharField(default='no school info', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='study_info',
            field=models.CharField(default='no study info', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_lastname',
            field=models.CharField(default='achternaam', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
    ]
