# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170511_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='campus_info',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_info',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_info',
            field=models.CharField(max_length=500),
        ),
    ]
