# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170511_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=100)),
                ('article_text', models.CharField(max_length=2000)),
                ('article_image', models.ImageField(blank=True, null=True, upload_to=b'')),
            ],
        ),
    ]
