# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='must_show',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
